openapi: 3.0.0
info:
  title: Student Beneficiary Service API
  description: API for exchanging student beneficiary information between CNRA and MENPS.
  version: 1.0.0
servers:
  - url: 'https://example.com/api'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # Common Schemas
    ProblemDetails:
      type: object
      description: An object representing an error response returned by the API.
      properties:
        type:
          type: string
          format: uri
          description: A URI reference that identifies the problem type. This provides a specific problem definition in a standardized form.
          example: "https://tools.ietf.org/html/rfc9110#section-15.5.1"
        title:
          type: string
          description: A short, human-readable summary of the problem type.
          example: "One or more validation errors occurred."
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 400
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
          example: "The provided data is not valid."
        instance:
          type: string
          description: A reference to this particular instance of the problem.
          example: "https://example.com/api/errors/12345"
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: An object containing field-specific details about the errors that occurred.
          example:
            Attribute:
              - "The value 'example' is not valid for the attribute."

    # Command and Response Schemas for Creating Campaign
    CreateCampaignCommand:
      type: object
      description: The command to create a new campaign, containing all necessary details about the campaign.
      required:
        - campaignId
        - campaignDate
        - totalStudentCount
      properties:
        campaignId:
          type: integer
          format: int64
          description: Reference of the campaign as an integer ID.
          example: 123456
        campaignDate:
          type: string
          format: date
          description: The date when the campaign is scheduled to start. It must not be future-dated or older than a week from today.
          example: '2024-02-14'
        totalStudentCount:
          type: integer
          description: The total number of students to be enrolled in the campaign. Must be a non-negative number.
          example: 200

    CreateCampaignResponse:
      type: object
      description: The response returned after creating a new campaign, including a success message and the campaign ID.
      properties:
        campaignId:
          type: integer
          format: int64
          description: The unique identifier of the newly created campaign.
          example: 123456

    # Command and Response Schemas for Sending Student Data
    SendStudentDataCommand:
      type: object
      description: The command for sending student data to be associated with a specific campaign. It includes batch information and a list of student data entries.
      required:
        - batchId
        - recordCount
        - students
      properties:
        batchId:
          type: integer
          description: The unique identifier for the batch of student data being submitted.
          example: 67890
        recordCount:
          type: integer
          description: The total number of student records included in the batch.
          example: 150
        students:
          type: array
          description: A list of student data entries. Each entry contains the student's MASSAR identifier and their status.
          items:
            $ref: '#/components/schemas/StudentData'
          example:
            - massarIdentifier: 'A123456790'
              status: 1
              idcsIdentifier: 5025081637
            - massarIdentifier: 'A123456789'
              status: 1
              idcsIdentifier: 5025081636
            - massarIdentifier: 'A987654321'
              status: 0
              idcsIdentifier: 5025081638
      example:
        batchId: 5
        recordCount: 3
        students:
          - massarIdentifier: 'A123456789'
            status: 1
            idcsIdentifier: 5025081636
          - massarIdentifier: 'A123456790'
            status: 1
            idcsIdentifier: 5025081637
          - massarIdentifier: 'D987654321'
            status: 0
            idcsIdentifier: 5025081638

    SendStudentDataResponse:
      type: object
      description: The response returned after creating a new campaign, including a success message and the campaign ID.
      properties:
        acceptedCount:
          type: integer
          description: The number of student records that were successfully accepted.
          example: 2
        rejectedCount:
          type: integer
          description: The number of student records that were rejected.
          example: 1
        rejectedDetails:
          type: array
          description: Detailed information about each rejected student record, including the MASSAR identifier and an error code indicating the reason for rejection.
          items:
            $ref: '#/components/schemas/RejectedStudentDetail'
          example:
            - massarIdentifier: 'D987654321'
              idcsIdentifier: 5025081638
              errorCode: 4000
              description: "Massar identifier not found in the student database."
         
      example:
        acceptedCount: 2
        rejectedCount: 1
        rejectedDetails:
            - massarIdentifier: 'D987654321'
              idcsIdentifier: 5025081638
              errorCode: 4000
              description: "Massar identifier not found in the student database."

    StudentData:
      type: object
      description: A data model representing individual student information, including the MASSAR identifier and activation status.
      properties:
        massarIdentifier:
          type: string
          description: The MASSAR identifier for the student. This is a unique identifier used in the educational system.
          example: 'A123456789'
        status:
          type: integer
          description: The status of the student in the campaign. A status of 0 indicates deactivation, while 1 indicates activation.
          example: 1
        idcsIdentifier:
          type: integer
          format: int64
          description: The Digital, Civil, and Social Identifier (IDCS) of the student.
          example: 5025081638

    RejectedStudentDetail:
      type: object
      description: "Provides detailed information about a student record that was rejected, including the reason for rejection."
      properties:
        massarIdentifier:
          type: string
          description: The MASSAR identifier of the student whose record was rejected.
          example: 'D987654321'
        idcsIdentifier:
          type: integer
          format: int64
          description: The Digital, Civil, and Social Identifier (IDCS) of the student.
          example: 5025081638
        errorCode:
          type: integer
          description: An error code that provides more detail about why the student record was rejected.
          example: 4000

tags:
  - name: Campaign Notification
    description: Operations related to campaign notification
  - name: Student Data
    description: Operations related to student data

paths:
  /campaigns:
    post:
      summary: Notify about the new campaign and provide student count
      description: Notifies MENPS of a new student beneficiary campaign, including its ID, start date, and expected student count.
      operationId: notifyCampaign
      tags:
        - Campaign Notification
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCampaignCommand'
      responses:
        '201':
          description: Campaign successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCampaignResponse'
        '400':
          description: Bad Request - Invalid input details
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type : https://tools.ietf.org/html/rfc9110#section-15.5.1
                title : One or more validation errors occurred.
                status : 400
                errors:
                  campaignId:
                    - "campaignId is required"
                    - "The provided campaignId already exists."
                  campaignDate:
                    - "campaignDate must be a valid date in the format YYYY-MM-DD"
                  totalStudentCount:
                    - "totalStudentCount must be greater than or equal to 0"
        '401':
          description: Unauthorized - Missing or invalid authentication token
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc7235#section-3.1
                title: Authentication Failure
                status: 401
                detail: The provided authentication token is missing or invalid. Please ensure you have provided a valid token.

  /campaigns/{campaignId}/students:
    post:
      summary: Send student beneficiary data
      description: Submits student data for a specific campaign by campaign ID.
      operationId: sendStudentData
      tags:
        - Student Data
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: campaignId
          required: true
          schema:
            type: integer
            format: int64
            description: Campaign identifier as an integer ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendStudentDataCommand'
      responses:
        '201':
          description: Successfully received student data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendStudentDataResponse'
        '400':
          description: Bad Request - Invalid input details
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type : https://tools.ietf.org/html/rfc9110#section-15.5.1
                title : One or more validation errors occurred.
                status : 400
                errors:
                  batchId:
                    - "batch id already exists in this campaign"
                    - "batchId must be a positive integer."
                  recordCount:
                    - "recordCount must be greater than or equal to 0"
                  students[0].massarIdentifier:
                    - "massarIdentifier is required."
                    - "massarIdentifier must be in correct format."
                  students[0].status:
                    - "status must be 0 or 1."
                  students[0].idcsIdentifier:
                    - "idcsIdentifier is required."
                    - "idcsIdentifier must be in correct format."

        '401':
          description: Unauthorized - Missing or invalid authentication token
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc7235#section-3.1
                title: Authentication Failure
                status: 401
                detail: The provided authentication token is missing or invalid. Please ensure you have provided a valid token.
        '404':
          description: Not Found - Campaign not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc7231#section-6.5.4
                title: Campaign not found
                status: 404
                detail: The specified campaign was not found.
